"""initial schema

Revision ID: 06a098bdf7f2
Revises: 
Create Date: 2026-03-28 19:02:56.873982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06a098bdf7f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('drivers_year_driver_number_key'), 'drivers', type_='unique')
    op.alter_column('pit_window_scores', 'recommendation',
               existing_type=postgresql.ENUM('EXTEND', 'PIT_SOON', 'PIT_NOW', name='pit_recommendation'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sessions', 'session_type',
               existing_type=postgresql.ENUM('Race', 'Qualifying', 'Practice 1', 'Practice 2', 'Practice 3', 'Sprint', 'Sprint Qualifying', name='session_type_enum'),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'session_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Race', 'Qualifying', 'Practice 1', 'Practice 2', 'Practice 3', 'Sprint', 'Sprint Qualifying', name='session_type_enum'),
               existing_nullable=True)
    op.alter_column('pit_window_scores', 'recommendation',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('EXTEND', 'PIT_SOON', 'PIT_NOW', name='pit_recommendation'),
               existing_nullable=False)
    op.create_unique_constraint(op.f('drivers_year_driver_number_key'), 'drivers', ['year', 'driver_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
