"""initial_schema

Revision ID: f43b863a5875
Revises: 
Create Date: 2026-04-16 05:22:52.984305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43b863a5875'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'driver_number', name='uq_drivers_year_driver_number')
    )
    op.create_table('meetings',
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('circuit_key', sa.Integer(), nullable=True),
    sa.Column('meeting_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('date_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('date_end', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('meeting_key')
    )
    op.create_table('tire_life_estimates',
    sa.Column('circuit_key', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=50), nullable=False),
    sa.Column('expected_laps_before_significant_deg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('avg_deg_onset_lap', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('sample_stint_count', sa.Integer(), nullable=False),
    sa.Column('avg_degradation_seconds_per_lap', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('circuit_key', 'compound')
    )
    op.create_table('sessions',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('meeting_key', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=True),
    sa.Column('date_start', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_key'], ['meetings.meeting_key'], ),
    sa.PrimaryKeyConstraint('session_key')
    )
    op.create_table('laps',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_duration', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('duration_sector_1', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('duration_sector_2', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('duration_sector_3', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.ForeignKeyConstraint(['year', 'driver_number'], ['drivers.year', 'drivers.driver_number'], ),
    sa.PrimaryKeyConstraint('session_key', 'year', 'driver_number', 'lap_number')
    )
    op.create_table('pit_stops',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('lane_duration', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('stop_duration', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.ForeignKeyConstraint(['year', 'driver_number'], ['drivers.year', 'drivers.driver_number'], ),
    sa.PrimaryKeyConstraint('session_key', 'year', 'driver_number', 'lap_number')
    )
    op.create_table('pit_window_scores',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=50), nullable=False),
    sa.Column('current_tyre_age_laps', sa.Integer(), nullable=False),
    sa.Column('current_avg_clean_lap_time_seconds', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('current_degradation_seconds_per_lap', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('expected_laps_before_significant_deg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('estimated_laps_remaining', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('recommendation', sa.String(length=20), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.ForeignKeyConstraint(['year', 'driver_number'], ['drivers.year', 'drivers.driver_number'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number', 'lap_number')
    )
    op.create_table('race_control',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.Integer(), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.ForeignKeyConstraint(['year', 'driver_number'], ['drivers.year', 'drivers.driver_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stint_pace_summary',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=50), nullable=False),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=False),
    sa.Column('clean_lap_count', sa.Integer(), nullable=False),
    sa.Column('avg_clean_lap_time_seconds', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('degradation_seconds_per_lap', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.ForeignKeyConstraint(['year', 'driver_number'], ['drivers.year', 'drivers.driver_number'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number', 'stint_number')
    )
    op.create_table('stints',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('stint_number', sa.Integer(), nullable=False),
    sa.Column('compound', sa.String(length=50), nullable=False),
    sa.Column('lap_start', sa.Integer(), nullable=False),
    sa.Column('lap_end', sa.Integer(), nullable=False),
    sa.Column('tyre_age_at_start', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_key'], ['sessions.session_key'], ),
    sa.ForeignKeyConstraint(['year', 'driver_number'], ['drivers.year', 'drivers.driver_number'], ),
    sa.PrimaryKeyConstraint('session_key', 'driver_number', 'stint_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stints')
    op.drop_table('stint_pace_summary')
    op.drop_table('race_control')
    op.drop_table('pit_window_scores')
    op.drop_table('pit_stops')
    op.drop_table('laps')
    op.drop_table('sessions')
    op.drop_table('tire_life_estimates')
    op.drop_table('meetings')
    op.drop_table('drivers')
    # ### end Alembic commands ###
